In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

!wget $data -O data-week-3.csv

--2026-10-25 12:16:16--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: ‘data-week-3.csv’

data-week-3.csv     100%[===================>] 954.59K  --.-KB/s    in 0.005s

2026-10-25 12:16:16 (196 MB/s) - ‘data-week-3.csv’ saved [977501/977501]

In [4]:
df = pd.read_csv('data-week-3.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.columns = df.columns.str.lower()
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [15]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [6]:
#convert all strings to lower and replace spaces with _
cat_cols = list(df.dtypes[df.dtypes=='str'].index)

for c in cat_cols:
    df[c] = df[c].str.lower().str.replace(' ','')

In [7]:
df.to_csv('data-week-3-tidyed.csv', index=False)

In [8]:
df = pd.read_csv('data-week-3-tidyed.csv')
df.head(10)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,nophoneservice,dsl,no,...,no,no,no,no,month-to-month,yes,electroniccheck,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,oneyear,no,mailedcheck,56.95,1889.50,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailedcheck,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,nophoneservice,dsl,yes,...,yes,yes,no,no,oneyear,no,banktransfer(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiberoptic,no,...,no,no,no,no,month-to-month,yes,electroniccheck,70.70,151.65,yes
5,9305-cdskc,female,0,no,no,8,yes,yes,fiberoptic,no,...,yes,no,yes,yes,month-to-month,yes,electroniccheck,99.65,820.50,yes
6,1452-kiovk,male,0,no,yes,22,yes,yes,fiberoptic,no,...,no,no,yes,no,month-to-month,yes,creditcard(automatic),89.10,1949.40,no
7,6713-okomc,female,0,no,no,10,no,nophoneservice,dsl,yes,...,no,no,no,no,month-to-month,no,mailedcheck,29.75,301.90,no
8,7892-pookp,female,0,yes,no,28,yes,yes,fiberoptic,no,...,yes,yes,yes,yes,month-to-month,yes,electroniccheck,104.80,3046.05,yes
9,6388-tabgu,male,0,no,yes,62,yes,no,dsl,yes,...,no,no,no,no,oneyear,no,banktransfer(automatic),56.15,3487.95,no

In [23]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                   str
dtype: object

In [9]:
df['seniorcitizen'].value_counts()

seniorcitizen
0    5901
1    1142
Name: count, dtype: int64

In [11]:
df.isnull().sum()

customerid           0
gender               0
seniorcitizen        0
partner              0
dependents           0
tenure               0
phoneservice         0
multiplelines        0
internetservice      0
onlinesecurity       0
onlinebackup         0
deviceprotection     0
techsupport          0
streamingtv          0
streamingmovies      0
contract             0
paperlessbilling     0
paymentmethod        0
monthlycharges       0
totalcharges        11
churn                0
dtype: int64

In [15]:
df[df['totalcharges'].isnull()]

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
488,4472-lvygi,female,0,yes,yes,0,no,nophoneservice,dsl,yes,...,yes,yes,yes,no,twoyear,yes,banktransfer(automatic),52.55,NaN,no
753,3115-czmzd,male,0,no,yes,0,yes,no,no,nointernetservice,...,nointernetservice,nointernetservice,nointernetservice,nointernetservice,twoyear,no,mailedcheck,20.25,NaN,no
936,5709-lvoeq,female,0,yes,yes,0,yes,no,dsl,yes,...,yes,no,yes,yes,twoyear,no,mailedcheck,80.85,NaN,no
1082,4367-nuyao,male,0,yes,yes,0,yes,yes,no,nointernetservice,...,nointernetservice,nointernetservice,nointernetservice,nointernetservice,twoyear,no,mailedcheck,25.75,NaN,no
1340,1371-dwpaz,female,0,yes,yes,0,no,nophoneservice,dsl,yes,...,yes,yes,yes,no,twoyear,no,creditcard(automatic),56.05,NaN,no
3331,7644-omvmy,male,0,yes,yes,0,yes,no,no,nointernetservice,...,nointernetservice,nointernetservice,nointernetservice,nointernetservice,twoyear,no,mailedcheck,19.85,NaN,no
3826,3213-vvolg,male,0,yes,yes,0,yes,yes,no,nointernetservice,...,nointernetservice,nointernetservice,nointernetservice,nointernetservice,twoyear,no,mailedcheck,25.35,NaN,no
4380,2520-sgtta,female,0,yes,yes,0,yes,no,no,nointernetservice,...,nointernetservice,nointernetservice,nointernetservice,nointernetservice,twoyear,no,mailedcheck,20.00,NaN,no
5218,2923-arzlg,male,0,yes,yes,0,yes,no,no,nointernetservice,...,nointernetservice,nointernetservice,nointernetservice,nointernetservice,oneyear,yes,mailedcheck,19.70,NaN,no
6670,4075-wkniu,female,0,yes,yes,0,yes,yes,dsl,no,...,yes,yes,yes,no,twoyear,no,mailedcheck,73.35,NaN,no
6754,2775-sefee,male,0,no,yes,0,yes,yes,dsl,yes,...,no,yes,no,no,twoyear,yes,banktransfer(automatic),61.90,NaN,no

In [19]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors="coerce")
df.totalcharges = df.totalcharges.fillna(0)
df.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [21]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                   str
dtype: object

In [22]:
df.churn = (df.churn=='yes').astype(int)

In [25]:
df.churn.value_counts()
df.to_csv('data-week-3-tidyed.csv', index=False)

**Validation**

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
df_full_train, df_test = train_test_split(df,test_size=0.2, random_state=1)
len(df), len(df_full_train), len(df_test)

(7043, 5634, 1409)

In [32]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df), len(df_full_train), len(df_test), len(df_val), len(df_train)

(7043, 5634, 1409, 1409, 4225)

In [38]:
#I think this is easier to read. 60-40 split. 60 = training data
#Split the remain 40% 50/50 between val and test
df_train, df_test = train_test_split(df,test_size=0.4, random_state=1)
df_test, df_val = train_test_split(df_test, test_size=0.5, random_state=1)
len(df), len(df_test), len(df_val), len(df_train)

(7043, 1409, 1409, 4225)

In [41]:
#Above randomises, with seed of 1
df_train.head()
#reset indexes
df_train.reset_index(drop=True, inplace=True)
df_val.reset_index(drop=True, inplace=True)
df_test.reset_index(drop=True, inplace=True)
df_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,5879-hmffh,female,0,yes,no,72,yes,yes,dsl,yes,...,yes,yes,yes,yes,twoyear,no,banktransfer(automatic),88.05,6520.80,0
1,8374-uulrv,male,0,no,no,72,yes,yes,dsl,yes,...,no,yes,yes,yes,twoyear,no,creditcard(automatic),86.05,6309.65,0
2,9447-yptbx,female,0,yes,no,50,yes,no,no,nointernetservice,...,nointernetservice,nointernetservice,nointernetservice,nointernetservice,oneyear,yes,banktransfer(automatic),19.85,943.10,0
3,4797-axpxk,female,0,no,yes,1,yes,no,dsl,yes,...,no,yes,no,no,month-to-month,yes,electroniccheck,60.00,60.00,1
4,9402-orrah,female,1,no,no,15,yes,no,fiberoptic,no,...,no,no,yes,yes,month-to-month,yes,electroniccheck,91.50,1400.30,0

In [45]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df.churn.values

del df_train['churn']
del df_val['churn']
del df_test['churn']

**EDA**

(7043, 1409, 1409, 4225)