In [2]:
import numpy as np
import pandas as pd
import matplot.lib.pyplot as plt

ModuleNotFoundError: No module named 'matplot'

In [5]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

!wget $data -O data-week-3.csv

--2026-10-25 12:16:16--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: ‘data-week-3.csv’

data-week-3.csv     100%[===================>] 954.59K  --.-KB/s    in 0.005s

2026-10-25 12:16:16 (196 MB/s) - ‘data-week-3.csv’ saved [977501/977501]

In [12]:
df = pd.read_csv('data-week-3.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
df.columns = df.columns.str.lower()
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [15]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [18]:
#convert all strings to lower and replace spaces with _
cat_cols = list(df.dtypes[df.dtypes=='str'].index)

for c in cat_cols:
    df[c] = df[c].str.lower().str.replace(' ','')

In [19]:
df.to_csv('data-week-3-tidyed.csv', index=False)

In [21]:
df = pd.read_csv('data-week-3-tidyed.csv')
df.head(10)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,nophoneservice,dsl,no,...,no,no,no,no,month-to-month,yes,electroniccheck,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,oneyear,no,mailedcheck,56.95,1889.50,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailedcheck,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,nophoneservice,dsl,yes,...,yes,yes,no,no,oneyear,no,banktransfer(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiberoptic,no,...,no,no,no,no,month-to-month,yes,electroniccheck,70.70,151.65,yes
5,9305-cdskc,female,0,no,no,8,yes,yes,fiberoptic,no,...,yes,no,yes,yes,month-to-month,yes,electroniccheck,99.65,820.50,yes
6,1452-kiovk,male,0,no,yes,22,yes,yes,fiberoptic,no,...,no,no,yes,no,month-to-month,yes,creditcard(automatic),89.10,1949.40,no
7,6713-okomc,female,0,no,no,10,no,nophoneservice,dsl,yes,...,no,no,no,no,month-to-month,no,mailedcheck,29.75,301.90,no
8,7892-pookp,female,0,yes,no,28,yes,yes,fiberoptic,no,...,yes,yes,yes,yes,month-to-month,yes,electroniccheck,104.80,3046.05,yes
9,6388-tabgu,male,0,no,yes,62,yes,no,dsl,yes,...,no,no,no,no,oneyear,no,banktransfer(automatic),56.15,3487.95,no

In [23]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                   str
dtype: object

In [26]:
df['seniorcitizen'].value_counts()

seniorcitizen
0    5901
1    1142
Name: count, dtype: int64